-- Task 15: For each transaction, calculate how much its amount differs from the average transaction amount calculated across all transactions for that specific account.
-- Goal: Identify transactions that are unusually large or small compared to the account's typical activity.
-- Display: account_id, transaction_id, transaction_date, amount, avg_account_transaction_amount, difference_from_avg.
