-- ===================================================================================================
-- TASK 1: Partition the Transactions Table by Date (Range Partitioning)
-- ===================================================================================================
--
-- DESCRIPTION:
-- Partition the `transactions` table by RANGE on the `transaction_date` column.
-- This helps improve query performance for date-based analytics.
--
-- GOAL:
-- Create monthly partitions for Jan, Feb, and Mar 2024.
--
-- ===================================================================================================
-- STEP 1: Recreate a new parent table
-- NOTE: For the purpose of this task, recreate a copy of the transactions table with the same structure.
-- Table name: transactions_partitioned
-- Partition key: transaction_date
-- ===================================================================================================

DROP TABLE IF EXISTS transactions_partitioned CASCADE;

CREATE TABLE transactions_partitioned (
    id                INT GENERATED BY DEFAULT AS IDENTITY,
    account_id        INT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    transaction_type  VARCHAR(20) CHECK (transaction_type IN ('deposit', 'withdrawal', 'transfer')) NOT NULL,
    amount            DECIMAL(15, 2) NOT NULL,
    transaction_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    target_account_id INT REFERENCES accounts(id) ON DELETE SET NULL,
    PRIMARY KEY (id, transaction_date)
) PARTITION BY RANGE (transaction_date);

-- ===================================================================================================
-- TODO STEP 2: Create 3 partitions
-- Partition Names:
--   transactions_2024_01 for Jan 2024
--   transactions_2024_02 for Feb 2024
--   transactions_2024_03 for Mar 2024
-- ===================================================================================================

-- ===================================================================================================
-- STEP 3: Verify that data lands in correct partition
-- ===================================================================================================

INSERT INTO transactions_partitioned(account_id, transaction_type, amount, transaction_date)
VALUES (1, 'deposit', 500.00, '2024-02-15');

-- Observation: Should go into transactions_2024_02
