-- ===================================================================================================
-- TASK 2: Partition the Accounts Table by Account Type (List Partitioning)
-- ===================================================================================================
--
-- DESCRIPTION:
-- Use LIST partitioning to split the `accounts` table into partitions based on `account_type`.
-- This allows PostgreSQL to optimize operations for each account category.
--
-- GOAL:
-- - Recreate `accounts_partitioned` table with LIST partitioning on `account_type`
-- - Create two partitions:
--      - checking_accounts
--      - savings_accounts
--
-- ===================================================================================================
-- STEP 1: Drop if exists
-- ===================================================================================================

DROP TABLE IF EXISTS accounts_partitioned CASCADE;

-- ===================================================================================================
-- STEP 2: Create Partitioned Table
-- TODO: Create correct primary key
-- ===================================================================================================

CREATE TABLE accounts_partitioned (
    id           INT GENERATED BY DEFAULT AS IDENTITY,
    customer_id  INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('checking', 'savings')),
    balance      DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) PARTITION BY LIST (account_type);

-- ===================================================================================================
-- TODO STEP 3: Create Partitions
-- - checking_accounts
-- - savings_accounts
-- ===================================================================================================


-- ===================================================================================================
-- STEP 4: Verify Partitioning with Sample Inserts
-- ===================================================================================================
-- Should go into checking_accounts:
INSERT INTO accounts_partitioned(customer_id, account_type, balance)
 VALUES (1, 'checking', 1200.00);
-- Should go into savings_accounts:
INSERT INTO accounts_partitioned(customer_id, account_type, balance)
 VALUES (2, 'savings', 3000.00);
----