-- ===================================================================================================
-- TASK 3: Add a Default Partition to Handle Unknown Account Types
-- ===================================================================================================
--
-- DESCRIPTION:
-- This task continues from Task 2, where we created a LIST-partitioned `accounts_partitioned` table
-- with partitions for 'checking' and 'savings'.
--
-- In this step, we will:
-- - Recreate the `accounts_partitioned` table with LIST partitioning on `account_type`
-- - Add two partitions for known types: 'checking' and 'savings'
-- - Add a DEFAULT partition to handle unexpected account types (e.g., 'investment')
--
-- GOAL:
-- - Ensure the system can gracefully store accounts with unknown `account_type`
--
-- ===================================================================================================
-- STEP 1: Drop Tables if They Exist
-- ===================================================================================================

DROP TABLE IF EXISTS default_accounts CASCADE;
DROP TABLE IF EXISTS checking_accounts CASCADE;
DROP TABLE IF EXISTS savings_accounts CASCADE;
DROP TABLE IF EXISTS accounts_partitioned CASCADE;

-- ===================================================================================================
-- STEP 2: Create Partitioned Table
-- ===================================================================================================

CREATE TABLE accounts_partitioned (
    id           INT GENERATED BY DEFAULT AS IDENTITY,
    customer_id  INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    account_type VARCHAR(20) NOT NULL,
    balance      DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, account_type)
) PARTITION BY LIST (account_type);

-- ===================================================================================================
-- TODO STEP 3: Create Known Partitions (checking_accounts and savings_accounts)
-- - checking_accounts
-- - savings_accounts
-- ===================================================================================================


-- ===================================================================================================
-- TODO STEP 4: Add Default Partition (name: default_accounts)
-- ===================================================================================================


-- ===================================================================================================
-- STEP 5: Insert a Row with an Unexpected Account Type
-- ===================================================================================================
-- Should go into default_accounts:
INSERT INTO accounts_partitioned(customer_id, account_type, balance)
VALUES (1, 'investment', 9999.99);
