-- ======================================================================================
-- TASK 4: Attach a Partition for Historical Transactions Older Than 2022
-- ======================================================================================
--
-- DESCRIPTION:
-- This task builds on the partitioning strategy where the `transactions_partitioned` table
-- is partitioned by RANGE on the `transaction_date` column.
--
-- You have received a large batch of historical transaction data dated before 2022.
-- To handle this efficiently, you will create a dedicated partition for all transactions
-- that occurred before January 1st, 2022.
--
-- GOAL:
-- - Recreate the `transactions_partitioned` table with RANGE partitioning
-- - Create and attach a partition for historical data before '2022-01-01'
-- - Insert a sample row to confirm the partitioning logic works correctly
--
-- ======================================================================================
-- STEP 1: Drop Existing Partitioned Table If Exists
-- ======================================================================================

DROP TABLE IF EXISTS transactions_partitioned CASCADE;

-- ======================================================================================
-- STEP 2: Create Partitioned Table
-- ======================================================================================

CREATE TABLE transactions_partitioned (
    id                INT GENERATED BY DEFAULT AS IDENTITY,
    account_id        INT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    transaction_type  VARCHAR(20) NOT NULL,
    amount            DECIMAL(15,2) NOT NULL,
    transaction_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    target_account_id INT,
    PRIMARY KEY (id, transaction_date)
) PARTITION BY RANGE (transaction_date);

-- ======================================================================================
-- TODO STEP 3: Create Partition for Data Before 2022
-- Table name: transactions_before_2022 range ('2000-01-01' -> '2022-01-01')
-- ======================================================================================

CREATE TABLE transactions_before_2022 PARTITION OF transactions_partitioned
    FOR VALUES FROM ('2000-01-01') TO ('2022-01-01');

-- ======================================================================================
-- STEP 4: Verify Partitioning with Sample Insert
-- ======================================================================================
-- Should go into transactions_before_2022:
INSERT INTO transactions_partitioned(account_id, transaction_type, amount, transaction_date)
VALUES (1, 'deposit', 100.00, '2021-10-01');
