-- ===================================================================================================
-- TASK 5: Partition Transactions by Year
-- ===================================================================================================
--
-- DESCRIPTION:
-- As part of ongoing efforts to improve performance and maintainability of the `transactions` table,
-- we now introduce year-based range partitioning. This approach helps efficiently organize and
-- query data based on the `transaction_date`, especially for large-scale financial applications
-- where transaction volume grows over time.
--
-- In this task, you will:
-- - Recreate the `transactions_partitioned` table, partitioned by RANGE on the `transaction_date`
-- - Define partitions for each of the years: 2022, 2023, and 2024
-- - Insert a sample row for the year 2023 and verify correct placement into the appropriate partition
--
-- NOTE:
-- To ensure compatibility with partitioning, the `PRIMARY KEY` must include the partitioning key
-- (i.e., `transaction_date`) along with a unique identifier such as `id`.
--
-- GOAL:
-- - Define the partitioned structure by year
-- - Add partitions for 2022–2024
-- - Insert test data to validate the configuration
--
-- ===================================================================================================
-- STEP 1: Drop Existing Partitioned Table (if any)
-- ===================================================================================================

DROP TABLE IF EXISTS transactions_2022 CASCADE;
DROP TABLE IF EXISTS transactions_2023 CASCADE;
DROP TABLE IF EXISTS transactions_2024 CASCADE;
DROP TABLE IF EXISTS transactions_partitioned CASCADE;

-- ===================================================================================================
-- STEP 2: Create Partitioned Table (By Range on transaction_date)
-- TODO: Add primary key
-- ===================================================================================================

CREATE TABLE transactions_partitioned (
    id                INT GENERATED BY DEFAULT AS IDENTITY,
    account_id        INT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    transaction_type  VARCHAR(20) NOT NULL,
    amount            DECIMAL(15,2) NOT NULL,
    transaction_date  TIMESTAMP NOT NULL,
    target_account_id INT
) PARTITION BY RANGE (transaction_date);

-- ===================================================================================================
-- TODO STEP 3: Create Yearly Partitions
-- Table name pattern: transactions_{year} ({value} - value placeholder)
-- ===================================================================================================


-- ===================================================================================================
-- STEP 4: Insert and Validate
-- ===================================================================================================

-- This transaction should be stored in the 2022, 2023, 2024 partitions:
INSERT INTO transactions_partitioned(account_id, transaction_type, amount, transaction_date)
        VALUES
            (1, 'withdrawal', 200.00, '2023-08-15'),
            (2, 'deposit', 150.00, '2022-05-10'),
            (3, 'transfer', 300.00, '2024-02-20');
