-- ===================================================================================================
-- TASK 7: Drop a Partition and Reassign Its Data
-- ===================================================================================================
--
-- DESCRIPTION:
-- In large partitioned tables, it’s common to archive and remove old partitions to:
-- - Improve query performance (by reducing scanned partitions)
-- - Save storage on hot/primary disks
-- - Simplify maintenance
--
-- In this task, we assume that a yearly partition `transactions_2023` already exists as part of the
-- `transactions_partitioned` table (range-partitioned by `transaction_date`). You will:
--
-- - Detach the 2023 partition
-- - Archive its data in a backup table
-- - Drop the detached table
--
-- GOAL:
-- - Ensure data is preserved before removing the partition
-- - Safely remove the partition from the parent table
-- - Confirm that the data still exists in a backup location
--
-- ===================================================================================================
-- STEP 1: Drop Existing Tables If Needed
-- ===================================================================================================

DROP TABLE IF EXISTS transactions_2022 CASCADE;
DROP TABLE IF EXISTS transactions_2023 CASCADE;
DROP TABLE IF EXISTS transactions_2024 CASCADE;
DROP TABLE IF EXISTS transactions_partitioned CASCADE;
DROP TABLE IF EXISTS transactions_2023_copy CASCADE;

-- ===================================================================================================
-- STEP 2: Create Partitioned Table
-- ===================================================================================================

CREATE TABLE transactions_partitioned (
    id                INT GENERATED BY DEFAULT AS IDENTITY,
    account_id        INT NOT NULL,
    transaction_type  VARCHAR(20) NOT NULL,
    amount            DECIMAL(15,2) NOT NULL,
    transaction_date  TIMESTAMP NOT NULL,
    target_account_id INT,
    PRIMARY KEY (id, transaction_date)
) PARTITION BY RANGE (transaction_date);

-- ===================================================================================================
-- TODO STEP 3: Create Partitions for 2022–2024
-- Table name pattern: transactions_{year} ({value} - value placeholder)
-- ===================================================================================================

CREATE TABLE transactions_2022 PARTITION OF transactions_partitioned
    FOR VALUES FROM ('2022-01-01') TO ('2023-01-01');

CREATE TABLE transactions_2023 PARTITION OF transactions_partitioned
    FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');

CREATE TABLE transactions_2024 PARTITION OF transactions_partitioned
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- ===================================================================================================
-- STEP 4: Insert Sample Data into 2023 Partition
-- ===================================================================================================
-- Goes into transactions_2023:
INSERT INTO transactions_partitioned(account_id, transaction_type, amount, transaction_date)
VALUES (100, 'withdrawal', 150.00, '2023-06-15');

-- ===================================================================================================
-- STEP 5: Archive and Detach Partition
-- ===================================================================================================

-- TODO Copy data to backup table (table name: transactions_2023_copy):
CREATE TABLE transactions_2023_copy AS
 SELECT * FROM transactions_2023;

-- TODO Detach partition from main table (becomes standalone)
ALTER TABLE transactions_partitioned
    DETACH PARTITION transactions_2023;

-- TODO Drop the now-detached partition
DROP TABLE transactions_2023;
