-- ===================================================================================================
-- TASK 8: Create Multi-Level Partitioning (By Year and Transaction Type)
-- ===================================================================================================
--
-- DESCRIPTION:
-- In analytical systems where queries often filter by both time and type of transaction,
-- performance can benefit from **multi-level partitioning** (aka subpartitioning).
--
-- In this task, we create a table `transactions_multilevel` that is:
-- - First partitioned by `transaction_date` using RANGE (one partition per year)
-- - Then subpartitioned by `transaction_type` using LIST (e.g., 'deposit', 'withdrawal')
--
-- This approach allows PostgreSQL to efficiently prune partitions during queries like:
--     WHERE transaction_date BETWEEN ... AND transaction_type = 'withdrawal'
--
-- GOAL:
-- - Create RANGE partitions by year (2023)
-- - Create LIST subpartitions by transaction type ('deposit', 'withdrawal')
-- - Insert a test record and verify correct routing
--
-- ===================================================================================================
-- STEP 1: Drop Existing Tables If Needed
-- ===================================================================================================

DROP TABLE IF EXISTS transactions_2023_withdrawal CASCADE;
DROP TABLE IF EXISTS transactions_2023_deposit CASCADE;
DROP TABLE IF EXISTS transactions_2023 CASCADE;
DROP TABLE IF EXISTS transactions_multilevel CASCADE;

-- ===================================================================================================
-- STEP 2: Create Multi-Level Partitioned Table
-- ===================================================================================================
-- TODO: add correct primary key
CREATE TABLE transactions_multilevel (
    id                INT GENERATED BY DEFAULT AS IDENTITY,
    account_id        INT NOT NULL,
    transaction_type  VARCHAR(20) NOT NULL,
    amount            DECIMAL(15,2) NOT NULL,
    transaction_date  TIMESTAMP NOT NULL
) PARTITION BY RANGE (transaction_date);

-- ===================================================================================================
-- TODO STEP 3: Create RANGE Partition for 2023 and Subpartition by transaction_type
-- Table name: transactions_2023
-- ===================================================================================================


-- ===================================================================================================
-- TODO STEP 4: Create LIST Subpartitions for transaction_type
-- - transactions_2023_deposit     for 'deposit'
-- - transactions_2023_withdrawal  for 'withdrawal'
-- ===================================================================================================


-- ===================================================================================================
-- STEP 5: Insert Sample Row to Trigger Multi-Level Routing
-- ===================================================================================================

-- This should go into transactions_2023_withdrawal (2023 + 'withdrawal')
INSERT INTO transactions_multilevel(account_id, transaction_type, amount, transaction_date)
VALUES (2, 'withdrawal', 500.00, '2023-05-20');
