-- ===================================================================================================
-- EXERCISE 3.2 Insert data using the new RANGE type
-- ===================================================================================================
-- Description:
--  Insert new rows into `accounts` setting `credit_limit`.
-- Sample Data:
--  1. id: 201, credit_limit: from inclusive 0 to exclusive 10000
--  2. id: 202, credit_limit: from inclusive 500 to inclusive 5000
--  3. id: 203, credit_limit: from exclusive 1000 to exclusive 15000
--  4. id: 204, credit_limit: from inclusive 0 to inclusive 0
--  5. id: 205, credit_limit: from inclusive 100 to inclusive 200
-- ===================================================================================================
-- WORKING AREA 👇