-- Task 9 (Potential Fraud Detection): Identify transactions where the amount is more than double the amount of the previous transaction for the *same account* on the *same day*.
-- Display account_id, transaction_id, transaction_date, amount, previous_transaction_amount.
