-- Task 10: For each customer, find the date of their first account opening and the date of their next account opening (if any).
-- Display customer_id, account_id, open_date, next_account_open_date. Order by customer_id, open_date.
