-- TASK 1: Transfer Funds Between Accounts
------------------------------------------------------------------------------------------------------------------------
-- DESCRIPTION:
-- In our banking application, users should be able to transfer funds between accounts.
-- This operation must be secure and consistent. It should check that the sender has sufficient balance,
-- deduct the amount from the sender’s account, credit the receiver’s account,
-- and log both transactions in the transactions table.
-- The system should raise an exception if either account is missing or the sender has insufficient funds.
--
-- PROCEDURE NAME: transfer_funds
-- INPUT PARAMETERS:
--   - p_sender_id (INT): The ID of the account sending funds.
--   - p_receiver_id (INT): The ID of the account receiving funds.
--   - p_amount (DECIMAL): The amount to transfer.
-- OUTPUT PARAMETERS:
--   - none (uses RAISE NOTICE to confirm successful transfer)
-- TIPS:
--   - Use CREATE OR REPLACE
--   - Validate that both accounts exist.
--   - Use FOR UPDATE to lock the sender account row.
--   - Ensure the sender has enough balance.
--   - Use transaction logging with target_account_id set for traceability.
------------------------------------------------------------------------------------------------------------------------


-- Sample call to verify functionality
-- Ensure these account IDs exist and sender has enough balance before running
-- CALL transfer_funds(1, 2, 100.00);

-- View updated balances
-- SELECT * FROM accounts WHERE id IN (1, 2);
-- SELECT * FROM transactions WHERE account_id IN (1, 2) ORDER BY id DESC LIMIT 5;
