------------------------------------------------------------------------------------------------------------------------
-- TASK 2: Reverse a Transaction
------------------------------------------------------------------------------------------------------------------------
-- DESCRIPTION:
-- This procedure reverses a transaction given its ID. It:
-- - Validates the transaction exists and is not already reversed.
-- - Inserts an inverse transaction with opposite amount.
-- - Updates the account balance accordingly.
-- - Raises exceptions for missing or invalid transactions.
-- - Check if transaction already reversed
--
-- PROCEDURE NAME: reverse_transaction
-- INPUT PARAMETERS:
--   - p_transaction_id (INT): The ID of the transaction to reverse.
-- OUTPUT PARAMETERS:
--   - none (uses RAISE NOTICE to confirm reversal)
-- TIPS:
--   - Use CREATE OR REPLACE.
--   - Ensure original transaction exists.
--   - Use negative amount to revert balance.
------------------------------------------------------------------------------------------------------------------------
