------------------------------------------------------------------------------------------------------------------------
-- TASK 5: Assign Branch Manager (with Constraints)
------------------------------------------------------------------------------------------------------------------------
-- DESCRIPTION:
-- This procedure assigns a given employee as the manager of a branch.
-- A branch can have only one manager, and a manager can be assigned to only one branch.
-- The procedure must check for and enforce these constraints before performing the assignment.
--
-- PROCEDURE NAME: assign_branch_manager
-- INPUT PARAMETERS:
--   - p_branch_id (INT): The ID of the branch.
--   - p_employee_id (INT): The ID of the employee to assign as manager.
-- OUTPUT PARAMETERS:
--   - none (uses RAISE NOTICE to confirm assignment)
-- TIPS:
--   - Validate that the branch and employee exist.
--   - Ensure the employee is not already managing another branch.
--   - Ensure the branch does not already have a manager.
--   - Update the branch’s manager_id field.
------------------------------------------------------------------------------------------------------------------------
