-- TASK 6: Approve Loan Application
------------------------------------------------------------------------------------------------------------------------
-- DESCRIPTION:
-- In our banking system, branch managers are responsible for approving loan applications.
-- This procedure will mark a loan as approved and record the manager who approved it.
-- It must ensure the following:
--   - The loan must exist and currently have a status of 'pending'.
--   - The branch must exist and must have a manager assigned.
--   - The provided manager must match the branch’s assigned manager.
--
-- PROCEDURE NAME: approve_loan_application
-- INPUT PARAMETERS:
--   - p_loan_id (INT): The ID of the loan to approve.
--   - p_manager_id (INT): The ID of the manager approving the loan.
-- OUTPUT:
--   - none (RAISE NOTICE on success)
--
-- TIPS:
--   - Use CREATE OR REPLACE
--   - Validate all conditions before updating the loan.
--   - Raise meaningful exceptions when validations fail.
------------------------------------------------------------------------------------------------------------------------

-- Sample usage:
-- CALL approve_loan_application(1, 10);
